# -*- coding: utf-8 -*-
"""aav_pr_ad_3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XztTjeoZI7ET5YNCbtanW5BIWStGZFlU
"""

def sum_nech(l):
    x = []
    for i in range(len(l)):
        if i % 2:
            x.append(l[i])
    return sum(x)

l = [2, 3, 5, 9, 3]
sum_nech(l)