# -*- coding: utf-8 -*-
"""AAV PR AD 5.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qakgjJj-6irj_opj7wU0EGNaY4HXChz
"""

def cod(t): # Кодирование
    s = []
    cnt = 0
    tmp = t[0]
    for i in range(len(t)):
        if t[i] == tmp:
            cnt += 1
        else:
            s.append(str(cnt))
            s.append(tmp)
            tmp = t[i]
            cnt = 1            
    s.append(str(cnt))
    s.append(tmp)
    return ''.join(s)

def decod(dt): # Декодирование
    dcod = []
    n = 1
    for i in dt[0:-1:2]:
        dcod.append(dt[n]*int(i))
        n += 2
    return ''.join(dcod)    



with open('ist_5.4.1.txt', 'r') as t1:
    t = t1.readline()
with open('rez_5.4.1.txt', 'w') as t2:
    t2.write(cod(t))
with open('ist_5.4.2.txt', 'r') as t3:
    dt = (t3.readline())
with open('rez_5.4.2.txt', 'w') as t2:
    t2.writelines(decod(dt))
print(t)
print(cod(t))
print(dt)
print(decod(dt))
t == decod(dt)