# -*- coding: utf-8 -*-
"""AAV_PR_AD_3_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1had8ugRFY8m-Qdr3hURA2veRWsXWDLkY
"""

def num_bin(x):
    bin_x = str()
    while x > 0:
        bin_x = str(x % 2) + bin_x
        x = x // 2
    return int(bin_x)

num_bin(45)