# -*- coding: utf-8 -*-
"""AAV_PR_AD_4_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IAp7ZA4jwMBMWQ8MM9a31bpbuwizCaL4
"""

def accur(d):
    import math
    return round(math.pi, d) if 1 <= d <= 10 else math.pi
accur(2)