# -*- coding: utf-8 -*-
"""AAV_PR_AD_4_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MClrHiTPiAYVZnioR-zmtdktnzjwyAb_
"""

def nonrepid(k):
    import random
    a = random.randint(1, 3) 
    if a == 1:
        return f'{random.randint(0, 100)} * x ** {k} + {random.randint(0, 100)} * x + {random.randint(0, 100)} = 0'
    elif a == 2:
        return f'x ** {k} + {random.randint(0, 100)} = 0'
    else: return f'{random.randint(0, 100)} * x ** {k} = 0'

nonrepid(3)