# -*- coding: utf-8 -*-
"""AAV PR AD 5.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qakgjJj-6irj_opj7wU0EGNaY4HXChz
"""

def cand(x, y):
    def zher(): # Жеребъевка
        import random
        return random.randint(1, 2)

    Player1 = 0 # ход игрока
    canP1 = 0 # количество конфет Player1
    Player2 = 0 # ход игрока
    canP2 = 0 # количество конфет Player2
    count = zher() # начальное значение счетчика
    while x > 0: # до тех пор пока конфеты есть))
        if y >= x: # макс. количество конфет хода не может прелышать остатка
            y = x
        print(f'остаток конфет - {x}, конфеты Pl1 - {canP1}, конфеты Pl2 - {canP2}')
        if count % 2 != 0:
            print(f'Player1, введите количество конфет от 1 до {y}')
            Player1 = int(input())
            count += 1
            if Player1 <= x:
                if Player1 > 28:
                    count -=1
                else:
                    canP1 += Player1
                    x -= Player1
        elif count % 2 == 0:
            print(f'Player2, введите количество конфет от 1 до {y}')
            Player2 = int(input())
            count += 1
            if Player2 <= x:
                if Player2 > 28:
                    count -=1
                else:
                    canP2 += Player2
                    x -= Player2
    else: 
      if count % 2 != 0:
          canP2 += canP1
          canP1 = 0
          print('Победил Player2!!!')
          print(f'Остаток конфет - {x}, Конфеты Pl1 - {canP1}, Конфеты Pl2 - {canP2}')  
      elif count % 2 == 0:
          canP1 += canP2
          canP2 = 0
          print('Победил Player1!!!')
          print(f'Остаток конфет - {x}, Конфеты Pl1 - {canP1}, Конфеты Pl2 - {canP2}')



x = 146 # остаток конфет
y = 28 # максимальное кол-во конфет на ход
cand(x, y)

# Player1 - "глупый". Выбор количества конфет осуществляется рандомно
# За Player2 играет челловек

def cand(x, y):
    import random
    def zher(): # Жеребъевка
        return random.randint(1, 2)

    Player1 = 0 # ход игрока
    canP1 = 0 # количество конфет Player1
    Player2 = 0 # ход игрока
    canP2 = 0 # количество конфет Player2
    count = zher() # начальное значение счетчика
    while x > 0: # до тех пор пока конфеты есть))
        if y >= x: # макс. количество конфет хода не может прелышать остатка
            y = x
        print(f'остаток конфет - {x}, конфеты Pl1 - {canP1}, конфеты Pl2 - {canP2}')
        if count % 2 != 0:
            Player1 = random.randint(1, y)
            count += 1
            print(f'Player1, забрал {Player1} конфет')
            # if Player1 <= x:
            #     if Player1 > 28:
            #         count -=1
            #     else:
            canP1 += Player1
            x -= Player1
        elif count % 2 == 0:
            print(f'Player2, введите количество конфет от 1 до {y}')
            Player2 = int(input())
            count += 1
            if Player2 <= x:
                if Player2 > 28:
                    count -=1
                else:
                    canP2 += Player2
                    x -= Player2
    else: 
      if count % 2 != 0:
          canP2 += canP1
          canP1 = 0
          print('Победил Player2!!!')
          print(f'Остаток конфет - {x}, Конфеты Pl1 - {canP1}, Конфеты Pl2 - {canP2}')  
      elif count % 2 == 0:
          canP1 += canP2
          canP2 = 0
          print('Победил Player1!!!')
          print(f'Остаток конфет - {x}, Конфеты Pl1 - {canP1}, Конфеты Pl2 - {canP2}')



x = 121 # остаток конфет
y = 28 # максимальное кол-во конфет на ход
cand(x, y)

# Player1 - "умный".
# За Player2 играет челловек

def cand(x, y):
    import random
    def zher(): # Жеребъевка
        return random.randint(1, 2)

    Player1 = 0 # ход игрока
    canP1 = 0 # количество конфет Player1
    Player2 = 0 # ход игрока
    canP2 = 0 # количество конфет Player2
    count = zher() # начальное значение счетчика
    while x > 0: # до тех пор пока конфеты есть))
        if y >= x: # макс. количество конфет хода не может прелышать остатка
            y = x
        print(f'остаток конф. - {x}, конф. Pl1 - {canP1}, конфе. Pl2 - {canP2}')
        if count % 2 != 0:
            if count == 1: # Если Player1 делает ход первым
                if x % (y + 1) > 0:
                    Player1 = x % (y + 1)
                    print(Player1)
                else:
                    Player1 = y
            elif x % (y + 1) > 0:
                Player1 = x % (y + 1)
            else:    
                Player1 = (y + 1) - Player2
            count += 1
            print(f'Player1, забрал {Player1} конф.')
            print()
            canP1 += Player1
            x -= Player1
        elif count % 2 == 0:
            print(f'Player2, введите количество конф. от 1 до {y}')
            print()
            Player2 = int(input())
            count += 1
            if Player2 <= x:
                if Player2 > 28:
                    count -=1
                else:
                    canP2 += Player2
                    x -= Player2
    else: 
      if count % 2 != 0:
          canP2 += canP1
          canP1 = 0
          print('Победил Player2!!!')
          print()
          print(f'Остаток конф. - {x}, Конф. Pl1 - {canP1}, Конф. Pl2 - {canP2}')  
      elif count % 2 == 0:
          canP1 += canP2
          canP2 = 0
          print('Победил Player1!!!')
          print()
          print(f'Остаток конф. - {x}, Конф. Pl1 - {canP1}, Конф. Pl2 - {canP2}')



x = 43 # остаток конфет
y = 5 # максимальное кол-во конфет на ход
cand(x, y)