# -*- coding: utf-8 -*-
"""AAV_PR_AD_4_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EDXduq9hTm0Dz-rb-06ksBbO_5IBPvZj
"""

f = open('file1.txt', 'r') # файл с первым многочленом
j = open('file2.txt', 'r') # фаил со вторым многочленом
s = open('resalt.txt', 'w') # файл для записи результата
x0 = f.readline()
y0 = j.readline()
z = str(eval(str(eval(x0)+eval(y0))))
s.write(z)
f.close()
j.close()
s.close()