# -*- coding: utf-8 -*-
"""aav_pr_ad_3_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iz_7JYJgyTmwmnf3KkaGIjctaZnkFqb8
"""

def sum_nech(l):
    x = []
    j = -1
    for i in range((len(l)+1)//2):
        x.append(l[i]*l[j])
        j += -1
    return (x)

l = [2, 3, 4, 5, 6]
sum_nech(l)