# -*- coding: utf-8 -*-
"""AAV_PR_AD_4_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-e9RSiMxhxfVZ6gmI86TzLYwBGxvGOU
"""

def nonrepid(n, a, b):
    import random
    return sorted(list(set([random.randint(a, b) for i in range(n)])))

nonrepid(22, 0, 99)