# -*- coding: utf-8 -*-
"""AAV_PR_AD_3_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VRjHByzFxlHwMIP4Ns31F4layHpo2Jq0
"""

def max_min(l):
    tmp = list()
    for i in l:
        tmp.append(i % 1)
    rz = (max(tmp) - min(tmp))
    return rz

l = [1.1, 1.2, 3.1, 5, 10.01]
print(max_min(l))