# -*- coding: utf-8 -*-
"""AAV PR AD 5.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qakgjJj-6irj_opj7wU0EGNaY4HXChz
"""

def worddel(t, a):
    with open('resalt_5.1.txt', 'w') as s:    
        return s.write(' '.join([x for x in str(*t).split() if a not in x]))


with open('исходный_текст_5.1.txt', 'r') as t:
    a = 'абв'
    worddel(t, a)