# -*- coding: utf-8 -*-
"""AAV PR AD 5.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qakgjJj-6irj_opj7wU0EGNaY4HXChz
"""

def resh9():# Рисуем рашетку (resh 3x3)
    for i in range(3):
        print (resh[0+i*3], "|", resh[1+i*3], "|", resh[2+i*3])
        if i != 2:
            print('-' * 9)

def action(num):# Действие игры
    y = 'O'
    if c % 2:
            y = 'X'
    print()
    print(f'Введите номер не занятой клетки для "{y}"')
    num = int(input())
    print()
    # y = 'O'
    if num >= 1 and num <= 9:
        # if c % 2:
            # y = 'X'
        resh[num - 1] = y

def win(resh):
    wr = [(0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)]# Условия победы 
    for i in wr:
        if resh[(i[0])] == resh[(i[1])] == resh[(i[2])]:
            return True


   
resh = [1, 2, 3, 4, 5, 6, 7, 8, 9]
num = None
c = 1 # Счетчик ходов
w = False
resh9()
for i in range(9):
    action(1)
    resh9()
    c += 1
    win(resh)
    tmp = win(resh)
    # print(tmp)
    if tmp:
        print ('Вы выйграли!')
        w = True
        break
    elif c == 9:
        print('Игра закончилась ничьёй!')