# -*- coding: utf-8 -*-
"""AAV_PR_AD_3_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yF7pIJ4xOp4C_wgG8WvYI9YHf20eZpkf
"""

def n_fib(n):
    a = 0
    b = 1
    c = 0
    x = [0, 1]
    for i in range(n - 1):
        c = a + b
        x.append(c)
        a = b
        b = c
    a = 0
    b = 1
    c = 0
    d = 0
    for i in range(n - 1):
        c = a - b
        x.insert(0, c)
        a = b
        b = c
    return x
    
n_fib(10)